### PR TITLE
Unifying boot, by using partition label resin-rootA/B instead of physical mmcblk0p2/3

### PR DESCRIPTION
**Pull request by theonlyzby**
Partition label to boot instead of physical one, in order to boot from SD Card, USB or HardDisk.
Cf Forum discussion with @agherzan
https://forums.resin.io/t/raspberry-to-run-resin-io-from-hard-disk/2413
resin-os/meta-resin#918

I hope this will help, Henry

### CODE REVIEW

**Comment by floion** [comment]
Hi. Let's make this PR to look correct, step by step.

First off, you have a commit which does nothing, it just adds a newline. So let's remove that.
When you want to work on existing commits in your tree, you work with "git rebase". First off, do a "git log -p" so that you see the history and identify the git commit you intend to modify. In this case, the commit you want to modify is identified by the revision ea5ef07dcb8afa78ea6579260de0e3591048d49e
So you use git rebase like this:

> git rebase -i ea5ef07dcb8afa78ea6579260de0e3591048d49e~

This will make git show you the rebase options for the selected commit. In this case, we want to remove it, as this commit is not good. So you will use the drop (or d) command instead of pick. So you write "d" (or "drop", whichever you prefer) in the git rebase options presented above and leave the rest unchanged and then save and exit.

After this, the rebase should finish and you should be able to force push this so that the pull request in github will appear without that unneeded commit. You should be able to do that with
> git push -f

and then go and check here in github that indeed that commit disappeared.

Second, when you do a git commit, please use the "-s" argument. This will "Add Signed-off-by line by the committer at the end of the commit log message" <- quote from the git commit help section. So that should be
> git commit -s

Your commits all lack the signed-off-by flag but you can still add this flag. You go through a similar procedure like above. Use "git rebase" again like above but this time pointing to a commit you want to add the signed-off-by flag. And when you are presented again with the rebase options, this time use "e" (or "edit") for the specific commit (you can even use git rebase to point to your oldest commit and then in the git rebase option window you set "edit" for multiple commits you want to modify) then save and exit. Afterwards, you just do
> git commit --amend --signoff

and followed by
> git rebase --continue

When all is done, again you should push the changes in the upstream pull request branch using
> git push -f

There are other things to change in this pull request, but let's start off with these.

Thank you

**Comment by theonlyzby** [comment]
@floion , 
I did the "git rebase -i ea5ef07~" and dropped that change (at least I think)
Then tried to follow your procedure with ups and downs, but at the end no errors anymore... are you more happy with that as it is now? btw, please tell me how to "sign-off" on the GIT web interface...???

So ... here you are now ... I let you proceed further, Henry

**Comment by floion** [comment]
I still see the commit you should have dropped in this pull request. So better try it again

**Comment by theonlyzby** [comment]
indeed, but when I "vi" this commit via "git rebase -i ea5ef07~", do I have to write (using i) "drop ea5ef07" or what??? if I read the doc dropping the line (noop) it should have deleted the file!?!
then I ":wq!" and continue the procedure...

**Comment by floion** [comment]
Yes, you need to use "drop" instead of the default "pick" for the commit you intend to drop.
And afterwards when the rebase is done, make sure you "git push -f"

**Comment by theonlyzby** [comment]
no ... sorry doesn't work!!! I tried every possible syntax I could imagine... I am lost! I have the impression I create more and more branches!?!

**Comment by floion** [comment]
You work on your existing local branch. None of the commands I referenced create branches so I don't think you create additional branches.

**Comment by theonlyzby** [comment]
OK ... good for this, but bad it doesn't drop that branch I accidentally created because I realized I forgot to put a good description ... and that's the only way I found on the Git web interface!
What do we do? Do you have commands you want me to try?

btw, do you have a how to submit a pull request document? Web and/or desktop/command line version?

**Comment by theonlyzby** [comment]
This is the output to the "git rebase -i ea5ef07~" command:
"
noop

# Rebase 38fc1c4..c409754 onto 38fc1c4 (1 command)
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
"
There is no pick ! What do I need to do? dd the noop line and i "drop ea5ef07~" on first line, then esc and :wq! ????

**Pull request closed without merging**
