### PR TITLE
Hotfix 2.0.6

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by willnewton** [comment]
I thought the fix here was updating meta-resin to the hotfix version?

**Comment by floion** [comment]
Yes @willnewton the hotfix version is in that maintenance branch

**Comment by floion** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
PR reviewed and jenkins build succeeded.
Will close this PR now without merging since I created a new branch called v2.0.6-maintenance that includes this PR and this new branch will be used to build the hotfix release from.

**Pull request closed without merging**
