### PR TITLE
Update to Yocto Sumo and release v2.13.1+rev1

### PR DESCRIPTION
**Pull request by agherzan**
This PR was tested in conjunction with https://github.com/resin-os/meta-resin/pull/1076. Make sure this PR includes a meta-resin update which has the above-mentioned PR.

### CODE REVIEW

**Comment by agherzan** [comment]
Thanks @floion. I agree with that.

**Comment by agherzan** [comment]
@floion did you get a chance to test this on a board? When you do, feel free to merge the PR.

**Comment by floion** [comment]
Will give it a go tomorrow

**Comment by agherzan** [comment]
Nice. Thanks @floion

**Pull request merged**
