### PR TITLE
Update warning in the dashboard regarding the RPi3 wifi connectivity.

### PR DESCRIPTION
**Pull request by imrehg**
Change-type: patch
Signed-off-by: Gergely Imreh <imrehg@gmail.com>

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins retest this please

**Comment by imrehg** [comment]
@agherzan isn't the `Changelog-entry` for the cases when the first line of the commit is not adequate? Added anyways...

**Comment by floion** [comment]
@imrehg this needs an explicit entry in the CHANGELOG.md file
We don't have versionbot on here yet

**Comment by imrehg** [comment]
Then `Changelog-entry` is definitely not needed. Updating again...

**Comment by imrehg** [comment]
@resin-jenkins retest this please

**Comment by mikesimos** [comment]
@resin-jenkins retest this please

**Pull request merged**
