### PR TITLE
Remove VCHQ workaround

### PR DESCRIPTION
**Pull request by agherzan**
@petrosagg @floion @telphan 

Connects to #26

### CODE REVIEW

**Comment by Page-** [comment]
What happens if someone uses their own base image?

**Comment by agherzan** [comment]
@Page- I'm not aware of this usecase but this fix should be release to upstream and included in official repos. So I would expect this to happen. CC @petrosagg @lorenzo-stoakes

**Comment by petrosagg** [comment]
@Page- the workaround isn't even enabled in our images. We put it there for custom builds. As Andrei said, at somepoint our fix will reach upstream and third party base images will get it

**Comment by floion** [comment]
LGTM

**Comment by lorenzo-stoakes** [comment]
Where does `fix-egl-apps-while-running-in-containers.patch` live? This doesn't look to be removed by this PR @agherzan ?

**Comment by lorenzo-stoakes** [comment]
Yeah still seems to [be there](https://github.com/resin-os/resin-raspberrypi/blob/163b1a61557d9a54b4f7ee72a58188464e200f0c/layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi-4.1/fix-egl-apps-while-running-in-containers.patch)

**Comment by agherzan** [comment]
Very good point @lorenzo-stoakes . I'll remove it.

**Comment by agherzan** [comment]
Fixed it @lorenzo-stoakes

**Comment by lorenzo-stoakes** [comment]
LGTM

**Pull request merged**
