### PR TITLE
[Issue #168] Unifying boot, by using partition label resin-rootA/B instead of physical mmcblk0p2/3

### PR DESCRIPTION
**Pull request by theonlyzby**
Partition label to boot instead of physical one, in order to boot from SD Card, USB or HardDisk.
Cf Forum discussion with @agherzan
https://forums.resin.io/t/raspberry-to-run-resin-io-from-hard-disk/2413
resin-os/meta-resin#918

I hope this will help, Henry

### CODE REVIEW

**Comment by theonlyzby** [comment]
Is there a major problem with this commit? Sorry if I made a mistake, but to solve previous issue, I tried re-commiting using the desktop app and not the web... :-(

**Comment by floion** [comment]
Yes, this PR still has problems.
Do you mind if we redo this PR?

**Comment by theonlyzby** [comment]
No, offcourse, not ... I want to learn and be able to do it on my own in the future! How do you want to proceed?

**Comment by floion** [comment]
@telphan can you pick this up and redo the changes proposed in this Pr in a new PR please?

**Comment by telphan** [comment]
@floion sure, will add this to my queue.

**Comment by theonlyzby** [comment]
@telphan, do you want me to do something? Do you have a "how-to" I could follow to submit this PR, please?

**Pull request closed without merging**
